version: "3.8"

services:
  frontend:
    image: th1enlm02/gameloft-frontend-ec2:latest
    container_name: gameloft-frontend
    ports:
      - "3000:80"
    restart: always
    env_file:
      - .env
